name: dummy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.3.0
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.2
  lottie: ^3.3.1
  flutter_localization: ^0.3.1
  connectivity_plus: ^6.1.3
  pretty_dio_logger: ^1.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/png/
    - assets/images/svg/
    - assets/lotties/
    - assets/videos/
#  fonts:
#    - family: Figtree
#      fonts:
#        - asset: assets/fonts/figtree/Figtree-Black.ttf